[package]
name = "penkmarket"
version = "1.0.0"
edition = "2024_07"

[features]
deprecated_legacy_map = []

[dependencies]
starknet = ">=2.3.0"

[[target.starknet-contract]]
sierra = true
casm = true
